//export { getAllPosts } from "./getAllPosts"
export { getCategories } from "./getCategories";
//export { getCategoryIdByUid } from "./getCategory"
//export { getCategoryPosts } from "./getCategoryPosts"
export { getLatestPosts } from "./getLatestPosts";
//export { getPostByUid } from "./getPostByUid"
export { getTags } from "./getTags";
export { getTagPosts } from "./getTagPosts";
//export { queryRepeatableDocuments } from "./queryRepeatableDocuments"
